keys:
  - &admin_sofi age1truyztzf0s5vq6r7cja84d9690l6q88cvlqqm6lpz3t7f7tkgdgqugqqtr
  - &server_nona age1ak8zjpcdgrup9yup79z0zc55qz7fqcmu54k7fl9xa2z8wxjcepgs5lh8er
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_sofi
        - *server_nona
  - path_regex: nixos/hosts/nona/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_sofi
        - *server_nona
