name: Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  "Nix-Flake":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V27
    - name: Run nix flake check
      run: nix flake check --no-build --show-trace

  "Pre-Commit":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V27
    - name: Run pre-commit-check
      run:  nix build .#checks.x86_64-linux.pre-commit-check --show-trace
