name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - name: Check Validate
      run: nix flake check --no-build --show-trace

  Validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - name: Check Validate
      run:  nix build .#checks.x86_64-linux.pre-commit-check --show-trace
