name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - name: Check Validate
      run: nix flake check --show-trace
