name: Update flake.lock
on:
  workflow_dispatch:  # allows manual triggering
  schedule:
    - cron: '37 5 * * 0'  # runs weekly on Sunday at 05:37.

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v18
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

